### ISSUE TITLE
`treehouses vnc auth vnc` output needs to change from passwd to password

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#2241] opened 2021-07-08 00:43 UTC
```
root@r144rpi4:~/cli# treehouses vnc auth vnc
Changing VNC server authentication to VNC password authentication way...
Writing 'Authentication=VncAuth' to config file
Create your password, run 'treehouses vnc passwd'.
Please reboot the system for changes to take effect.
root@r144rpi4:~/cli# treehouses vnc passwd raspberry
Error: only 'on', 'off', 'info', 'auth', 'password' options are supported
root@r144rpi4:~/cli# treehouses vnc password raspberry
```

**Comment by xyb994** [comment] 2024-06-25 18:59
duplicate of #2136

**Closed by xyb994** 2024-06-25 18:59 UTC
